# Generated by Django 5.2.6 on 2025-10-03 21:35

import django.contrib.auth.models
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("peanuts", "Peanuts"),
                            ("seafood", "Seafood"),
                            ("dairy", "Dairy"),
                            ("gluten", "Gluten"),
                            ("eggs", "Eggs"),
                            ("soy", "Soy"),
                            ("tree_nuts", "Tree Nuts"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "boundary",
                    models.JSONField(blank=True, null=True, help_text="GeoJSON Polygon"),
                ),
                (
                    "average_meal_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("Africa/Abidjan", "Africa/Abidjan (GMT)"),
                            ("Africa/Accra", "Africa/Accra (GMT)"),
                            ("Africa/Addis_Ababa", "Africa/Addis Ababa (EAT, +03:00)"),
                            ("Africa/Algiers", "Africa/Algiers (CET, +01:00)"),
                            ("Africa/Cairo", "Africa/Cairo (EET, +02:00)"),
                            ("Africa/Casablanca", "Africa/Casablanca (+01:00)"),
                            (
                                "Africa/Johannesburg",
                                "Africa/Johannesburg (SAST, +02:00)",
                            ),
                            ("Africa/Lagos", "Africa/Lagos (WAT, +01:00)"),
                            ("Africa/Nairobi", "Africa/Nairobi (EAT, +03:00)"),
                            ("Africa/Tunis", "Africa/Tunis (CET, +01:00)"),
                            ("America/Anchorage", "America/Anchorage (AKST, -09:00)"),
                            (
                                "America/Argentina/Buenos_Aires",
                                "America/Buenos Aires (ART, -03:00)",
                            ),
                            ("America/Bogota", "America/Bogota (COT, -05:00)"),
                            ("America/Caracas", "America/Caracas (VET, -04:00)"),
                            ("America/Chicago", "America/Chicago (CST, -06:00)"),
                            ("America/Denver", "America/Denver (MST, -07:00)"),
                            (
                                "America/Los_Angeles",
                                "America/Los Angeles (PST, -08:00)",
                            ),
                            (
                                "America/Mexico_City",
                                "America/Mexico City (CST, -06:00)",
                            ),
                            ("America/New_York", "America/New York (EST, -05:00)"),
                            ("America/Sao_Paulo", "America/Sao Paulo (BRT, -03:00)"),
                            ("America/Toronto", "America/Toronto (EST, -05:00)"),
                            ("America/Vancouver", "America/Vancouver (PST, -08:00)"),
                            ("Asia/Baghdad", "Asia/Baghdad (AST, +03:00)"),
                            ("Asia/Bangkok", "Asia/Bangkok (ICT, +07:00)"),
                            ("Asia/Beijing", "Asia/Beijing (CST, +08:00)"),
                            ("Asia/Dhaka", "Asia/Dhaka (BST, +06:00)"),
                            ("Asia/Dubai", "Asia/Dubai (GST, +04:00)"),
                            ("Asia/Hong_Kong", "Asia/Hong Kong (HKT, +08:00)"),
                            ("Asia/Jakarta", "Asia/Jakarta (WIB, +07:00)"),
                            ("Asia/Jerusalem", "Asia/Jerusalem (IST, +02:00)"),
                            ("Asia/Karachi", "Asia/Karachi (PKT, +05:00)"),
                            ("Asia/Kolkata", "Asia/Kolkata (IST, +05:30)"),
                            ("Asia/Kuala_Lumpur", "Asia/Kuala Lumpur (MYT, +08:00)"),
                            ("Asia/Manila", "Asia/Manila (PHT, +08:00)"),
                            ("Asia/Riyadh", "Asia/Riyadh (AST, +03:00)"),
                            ("Asia/Seoul", "Asia/Seoul (KST, +09:00)"),
                            ("Asia/Shanghai", "Asia/Shanghai (CST, +08:00)"),
                            ("Asia/Singapore", "Asia/Singapore (SGT, +08:00)"),
                            ("Asia/Taipei", "Asia/Taipei (CST, +08:00)"),
                            ("Asia/Tokyo", "Asia/Tokyo (JST, +09:00)"),
                            (
                                "Australia/Melbourne",
                                "Australia/Melbourne (AEDT, +11:00)",
                            ),
                            ("Australia/Perth", "Australia/Perth (AWST, +08:00)"),
                            ("Australia/Sydney", "Australia/Sydney (AEDT, +11:00)"),
                            ("Pacific/Auckland", "Pacific/Auckland (NZDT, +13:00)"),
                            ("Pacific/Fiji", "Pacific/Fiji (FJT, +12:00)"),
                            ("Pacific/Honolulu", "Pacific/Honolulu (HST, -10:00)"),
                            ("Europe/Amsterdam", "Europe/Amsterdam (CET, +01:00)"),
                            ("Europe/Athens", "Europe/Athens (EET, +02:00)"),
                            ("Europe/Berlin", "Europe/Berlin (CET, +01:00)"),
                            ("Europe/Brussels", "Europe/Brussels (CET, +01:00)"),
                            ("Europe/Bucharest", "Europe/Bucharest (EET, +02:00)"),
                            ("Europe/Dublin", "Europe/Dublin (GMT)"),
                            ("Europe/Istanbul", "Europe/Istanbul (TRT, +03:00)"),
                            ("Europe/Lisbon", "Europe/Lisbon (WET)"),
                            ("Europe/London", "Europe/London (GMT)"),
                            ("Europe/Madrid", "Europe/Madrid (CET, +01:00)"),
                            ("Europe/Moscow", "Europe/Moscow (MSK, +03:00)"),
                            ("Europe/Paris", "Europe/Paris (CET, +01:00)"),
                            ("Europe/Rome", "Europe/Rome (CET, +01:00)"),
                            ("Europe/Stockholm", "Europe/Stockholm (CET, +01:00)"),
                            ("Europe/Vienna", "Europe/Vienna (CET, +01:00)"),
                            ("Europe/Warsaw", "Europe/Warsaw (CET, +01:00)"),
                            ("Europe/Zurich", "Europe/Zurich (CET, +01:00)"),
                            ("UTC", "UTC (Coordinated Universal Time)"),
                        ],
                        default="UTC",
                        help_text="IANA timezone name (e.g., 'Africa/Lagos', 'America/New_York')",
                        max_length=63,
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=2, unique=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217 currency code (e.g. NGN, USD, EUR, GBP)",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full currency name (e.g. Nigerian Naira, US Dollar)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Currency symbol (e.g. ₦, $, €, £)", max_length=5
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FitnessGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Weight Loss"),
                            ("muscle_gain", "Muscle Gain"),
                            ("maintenance", "Maintenance"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("diabetes", "Diabetes"),
                            ("hypertension", "Hypertension"),
                            ("high_cholesterol", "High Cholesterol"),
                            ("anemia", "Anemia"),
                            ("celiac", "Celiac Disease"),
                            ("lactose_intolerance", "Lactose Intolerance"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PreferredCuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("vegan_vegetarian", "Vegan Vegetarian"),
                            ("nigerian", "Nigerian"),
                            ("ghanaian", "Ghanaian"),
                            ("ethiopian", "Ethiopian"),
                            ("moroccan", "Moroccan"),
                            ("italian", "Italian"),
                            ("french", "French"),
                            ("spanish", "Spanish"),
                            ("greek", "Greek"),
                            ("british", "British"),
                            ("chinese", "Chinese"),
                            ("japanese", "Japanese"),
                            ("korean", "Korean"),
                            ("thai", "Thai"),
                            ("indian", "Indian"),
                            ("vietnamese", "Vietnamese"),
                            ("filipino", "Filipino"),
                            ("american", "American"),
                            ("mexican", "Mexican"),
                            ("brazilian", "Brazilian"),
                            ("argentinian", "Argentinian"),
                            ("caribbean", "Caribbean"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "point",
                    models.JSONField(blank=True, null=True, help_text="GeoJSON Point"),
                ),
                ("email", models.CharField(blank=True, max_length=250, null=True)),
                ("website", models.URLField(blank=True, max_length=250, null=True)),
                ("social", models.URLField(blank=True, max_length=250, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=100, unique=True)),
                (
                    "average_meal_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number (e.g., +2348044467208).",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "allergies",
                    models.ManyToManyField(
                        blank=True, related_name="users", to="api.allergy"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="api.city",
                    ),
                ),
                (
                    "fitness_goals",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="api.fitnessgoal",
                    ),
                ),
                (
                    "health_conditions",
                    models.ManyToManyField(
                        blank=True, related_name="users", to="api.healthcondition"
                    ),
                ),
                (
                    "preferred_cuisine",
                    models.ManyToManyField(
                        blank=True, related_name="user", to="api.preferredcuisine"
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cities",
                to="api.currency",
            ),
        ),
        migrations.CreateModel(
            name="DeliveryAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("point", models.JSONField(blank=True, null=True, help_text="GeoJSON Point")),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Address",
                "verbose_name_plural": "Delivery Addresses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("image_url", models.ImageField(blank=True, null=True, upload_to="")),
                ("available", models.BooleanField(default=True)),
                (
                    "times_of_day",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("morning", "Morning"),
                                ("afternoon", "Afternoon"),
                                ("evening", "Evening"),
                            ],
                            max_length=50,
                        ),
                        blank=True,
                        default=list,
                        help_text="Times of day this meal is go for (e.g., morning, afternoon, evening)",
                        size=None,
                    ),
                ),
                (
                    "calories",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "carbs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fats",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fiber",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "sugar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "sodium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "cholesterol",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "serving_amount_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total weight in grams (g) of one serving of this meal, including all components",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meals",
                        to="api.city",
                    ),
                ),
                (
                    "fitness_goals",
                    models.ManyToManyField(
                        blank=True, related_name="meals", to="api.fitnessgoal"
                    ),
                ),
                (
                    "restricted_allergies",
                    models.ManyToManyField(
                        blank=True, related_name="meals", to="api.allergy"
                    ),
                ),
                (
                    "restricted_health_conditions",
                    models.ManyToManyField(
                        blank=True, related_name="meals", to="api.healthcondition"
                    ),
                ),
                (
                    "cuisine",
                    models.ManyToManyField(
                        blank=True, related_name="meals", to="api.preferredcuisine"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meals",
                        to="api.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pickup_street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pickup_point",
                    models.JSONField(blank=True, null=True, help_text="GeoJSON Point"),
                ),
                (
                    "dropoff_street_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dropoff_point",
                    models.JSONField(blank=True, null=True, help_text="GeoJSON Point"),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatched", "Dispatched"),
                            ("arrived", "Arrived"),
                            ("received", "Received"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "ordered_via",
                    models.CharField(
                        choices=[("whatsapp", "Whatsapp"), ("online", "Online")],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=250, null=True)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("meal_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("delivery_fee", models.DecimalField(decimal_places=2, max_digits=8)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=8)),
                ("paid", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="api.currency",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="api.meal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="city",
            name="preferred_cuisine",
            field=models.ManyToManyField(
                blank=True, related_name="cities", to="api.preferredcuisine"
            ),
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "time_of_day",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "choice_option",
                    models.CharField(
                        choices=[("first", "First"), ("second", "Second")],
                        max_length=20,
                    ),
                ),
                ("day", models.DateField(default=django.utils.timezone.now)),
                ("sent_to_user", models.BooleanField(default=False)),
                ("accepted", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="api.meal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("neutral", "Neutral"),
                            ("hate", "Hate"),
                        ],
                        max_length=7,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="api.meal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="states",
                        to="api.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "ordering": ["-created_at"],
                "unique_together": {("name", "country")},
            },
        ),
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cities",
                to="api.state",
            ),
        ),
        migrations.CreateModel(
            name="AIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model", models.CharField(default="gpt-5-nano", max_length=50)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "prompt_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "completion_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("intent", models.CharField(blank=True, max_length=50, null=True)),
                ("tool_calls_count", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="api_aiusage_user_id_a5cffb_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="api_aiusage_created_2fefeb_idx"
                    ),
                    models.Index(fields=["model"], name="api_aiusage_model_154e62_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MealPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preference",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("neutral", "Neutral"),
                            ("hate", "Hate"),
                        ],
                        max_length=7,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_preferences",
                        to="api.meal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "meal")},
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_id", models.CharField(max_length=250, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("bot", "Bot")], max_length=10
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("resp", models.JSONField(blank=True, null=True)),
                (
                    "preview_media",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "current_intent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_intent", "No Intent"),
                            ("menu_options", "Menu Options"),
                            ("registered", "Registered"),
                            ("set_preference", "Set Preference"),
                            ("update_preference", "Update Preference"),
                            ("first_location", "First Location"),
                            ("recommended_meals", "Recommended Meals"),
                            (
                                "pick_delivery_address_option",
                                "Pick Delivery Address Option",
                            ),
                            (
                                "add_new_order_delivery_address",
                                "Add New Order Delivery Address",
                            ),
                            ("number_of_plates", "Number of Plates"),
                            ("pay_for_order", "Pay for Order"),
                            ("order_placed", "Order Placed"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="api.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("role", "user"),
                            models.Q(
                                ("role", "bot"),
                                models.Q(("current_intent", None), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="bot_messages_require_current_intent",
                    )
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name", "state")},
        ),
    ]
