# Generated by Django 5.2.6 on 2025-10-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AIUsage",
        ),
    ]
