# Generated by Django 5.2.6 on 2025-09-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="average_meal_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="preferredcuisine",
            name="name",
            field=models.CharField(
                choices=[("nigerian", "Nigerian"), ("chinese", "Chinese")],
                max_length=100,
            ),
        ),
    ]
