# Generated by Django 5.2.6 on 2025-10-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_aiusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="code",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="current_intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_intent", "No intent"),
                    ("needs_reply", "Needs reply"),
                    ("completed_reply", "Completed reply"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
