# Generated by Django 5.2.6 on 2025-12-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_restaurant_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
