# Generated by Django 5.2.6 on 2025-09-29 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_city_average_meal_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="like_but_dislike_preparation",
        ),
        migrations.AlterField(
            model_name="message",
            name="current_intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_intent", "No Intent"),
                    ("registered", "Registered"),
                    ("set_preference", "Set Preference"),
                    ("update_preference", "Update Preference"),
                    ("first_location", "First Location"),
                    ("first_location_retry", "First Location Retry"),
                    ("recommended_meals", "Recommended Meals"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preferredcuisine",
            name="name",
            field=models.CharField(
                choices=[
                    ("vegan_vegetarian", "Vegan Vegetarian"),
                    ("nigerian", "Nigerian"),
                    ("ghanaian", "Ghanaian"),
                    ("ethiopian", "Ethiopian"),
                    ("moroccan", "Moroccan"),
                    ("italian", "Italian"),
                    ("french", "French"),
                    ("spanish", "Spanish"),
                    ("greek", "Greek"),
                    ("british", "British"),
                    ("chinese", "Chinese"),
                    ("japanese", "Japanese"),
                    ("korean", "Korean"),
                    ("thai", "Thai"),
                    ("indian", "Indian"),
                    ("vietnamese", "Vietnamese"),
                    ("filipino", "Filipino"),
                    ("american", "American"),
                    ("mexican", "Mexican"),
                    ("brazilian", "Brazilian"),
                    ("argentinian", "Argentinian"),
                    ("caribbean", "Caribbean"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="MealPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preference",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("neutral", "Neutral"),
                            ("hate", "Hate"),
                        ],
                        max_length=7,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_preferences",
                        to="api.meal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "meal")},
            },
        ),
    ]
