# Generated by Django 5.2.6 on 2025-09-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_conv_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="conv",
        ),
        migrations.AddField(
            model_name="user",
            name="current_intent",
            field=models.CharField(
                blank=True,
                choices=[("registered", "Registered")],
                max_length=100,
                null=True,
            ),
        ),
    ]
