# Generated by Django 5.2.6 on 2025-12-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_meal_note_alter_meal_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="preview_media",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
