# Generated by Django 5.2.6 on 2025-10-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_order_code_alter_message_current_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="embedding",
            field=models.JSONField(
                blank=True,
                help_text="Cached embedding vector for similarity search",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="embedding_generated_at",
            field=models.DateTimeField(
                blank=True, help_text="When the embedding was last generated", null=True
            ),
        ),
    ]
