# Generated by Django 5.2.6 on 2025-09-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_user_conv_user_current_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferredcuisine",
            name="name",
            field=models.CharField(
                choices=[
                    ("vegan_vegetarian", "Vegan Vegetarian"),
                    ("nigerian", "Nigerian"),
                    ("chinese", "Chinese"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="current_intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registered", "Registered"),
                    ("fitness_goal", "Fitness Goal"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
