# Generated by Django 5.2.6 on 2025-12-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_change_preview_media_to_urlfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="preview_media",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
