# Generated by Django 5.2.6 on 2025-09-30 14:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_city_timezone_recommendation_sent_to_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="times_of_day",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("morning", "Morning"),
                        ("afternoon", "Afternoon"),
                        ("evening", "Evening"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="api.deliveryaddress",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="current_intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_intent", "No Intent"),
                    ("menu_options", "Menu Options"),
                    ("registered", "Registered"),
                    ("set_preference", "Set Preference"),
                    ("update_preference", "Update Preference"),
                    ("first_location", "First Location"),
                    ("first_location_retry", "First Location Retry"),
                    ("recommended_meals", "Recommended Meals"),
                    ("pick_delivery_address_option", "Pick Delivery Address Option"),
                    (
                        "add_new_order_delivery_address",
                        "Add New Order Delivery Address",
                    ),
                    ("number_of_plates", "Number of Plates"),
                    ("pay_for_order", "Pay for Order"),
                    ("order_placed", "Order Placed"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
