# Generated by Django 5.2.6 on 2025-11-15 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_appsettings_user_current_referral_earnings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appsettings",
            name="referral_bonus",
        ),
        migrations.AddField(
            model_name="appsettings",
            name="whatsapp_support_phone_number",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="city",
            name="referral_bonus",
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referralearning",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referral_earnings",
                to="api.currency",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="minimum_withdrawal",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="whatsapp_phone_number",
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
