# Generated by Django 5.2.6 on 2025-12-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_message_preview_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="last_stock_reset_date",
            field=models.DateField(
                blank=True,
                help_text="Last date when stock was reset. Used for lazy daily reset based on city timezone.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="remaining_stock",
            field=models.IntegerField(
                blank=True,
                help_text="Current remaining stock for today. Auto-resets daily when first order is placed.",
                null=True,
            ),
        ),
    ]
