# Generated by Django 5.2.6 on 2025-09-30 15:15

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_meal_times_of_day_order_delivery_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=250, null=True)),
                ("website", models.URLField(blank=True, max_length=250, null=True)),
                ("social", models.URLField(blank=True, max_length=250, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="meal",
            name="times_of_day",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("morning", "Morning"),
                        ("afternoon", "Afternoon"),
                        ("evening", "Evening"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="Times of day this meal is go for (e.g., morning, afternoon, evening)",
                size=None,
            ),
        ),
    ]
