# Generated by Django 5.2.6 on 2025-11-15 21:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_appsettings_referral_bonus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance_type",
                    models.CharField(
                        choices=[
                            ("referral", "Referral Earnings"),
                            ("wallet", "Wallet Balance"),
                            ("bonus", "Bonus Balance"),
                        ],
                        help_text="Type of balance (referral, wallet, bonus, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Balance amount in the specified currency",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_balances",
                        to="api.currency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Balance",
                "verbose_name_plural": "User Balances",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "balance_type"],
                        name="api_userbal_user_id_4b87c4_idx",
                    ),
                    models.Index(
                        fields=["user", "balance_type", "currency"],
                        name="api_userbal_user_id_d918c2_idx",
                    ),
                ],
                "unique_together": {("user", "balance_type", "currency")},
            },
        ),
    ]
