# Generated by Django 5.2.6 on 2025-09-30 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_restaurant_alter_meal_times_of_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meals",
                to="api.restaurant",
            ),
            preserve_default=False,
        ),
    ]
