# Generated by Django 5.2.6 on 2025-11-15 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_userbalance"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralearning",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referral_earnings",
                to="api.city",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="withdrawals",
                to="api.currency",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdrawals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
