# Generated by Django 5.2.6 on 2025-12-24 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_nonreachedarea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="remaining_stock",
            field=models.IntegerField(
                blank=True, help_text="Current remaining stock for today.", null=True
            ),
        ),
        migrations.CreateModel(
            name="BroadcastMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.TextField(help_text="The message content to send to users"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional image URL to send with the message",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("total_eligible", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select cities to send to. Leave empty to send to ALL cities.",
                        related_name="broadcast_messages",
                        to="api.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast Message",
                "verbose_name_plural": "Broadcast Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SingleUserMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(help_text="The message content to send")),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional image URL to send with the message",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Select the user to send the message to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Single User Message",
                "verbose_name_plural": "Single User Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
