# Generated by Django 5.2.6 on 2025-09-30 20:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_meal_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_address",
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="dropoff_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="dropoff_street_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="meal_price",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_street_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
