# Generated by Django 5.2.6 on 2025-09-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_meal_currency_remove_order_delivery_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="currency",
        ),
    ]
