# Generated by Django 5.2.6 on 2025-11-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_referralearning_city_withdrawal_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="current_referral_earnings",
        ),
    ]
