# Generated by Django 5.2.6 on 2025-12-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_meal_remaining_stock_broadcastmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="original_image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="image"
            ),
        ),
    ]
