# Generated by Django 5.2.6 on 2025-11-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_user_current_referral_earnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
