# Generated by Django 5.2.6 on 2025-12-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_meal_original_image_url_alter_meal_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="meal",
            name="original_image_url",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
