# Generated by Django 5.2.6 on 2025-12-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_meal_image_url_alter_meal_original_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="original_image_url",
        ),
    ]
