# Generated by Django 5.2.6 on 2025-11-29 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_meal_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="meal",
        ),
        migrations.AddField(
            model_name="review",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="api.order",
            ),
            preserve_default=False,
        ),
    ]
