# Generated by Django 5.2.6 on 2025-12-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_meal_original_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="inactive_but_still_recommend",
            field=models.BooleanField(
                default=False,
                help_text="Set to True to disable this restaurant and all its meals",
            ),
        ),
    ]
