# Generated by Django 5.2.6 on 2025-12-01 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_review_meal_review_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="meal_rating",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Meal rating from 1 to 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
