# Generated by Django 5.2.6 on 2025-12-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_review_meal_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="current_intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_intent", "No intent"),
                    ("needs_reply", "Needs reply"),
                    ("reminder_message", "Reminder message"),
                    ("completed_reply", "Completed reply"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
