# Generated by Django 5.2.6 on 2025-12-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_restaurant_inactive_but_still_recommend"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_message_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has been sent the referral invitation message",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_reminder_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has been sent the registration completion reminder",
            ),
        ),
    ]
