# Generated by Django 5.2.6 on 2025-12-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_user_referral_message_sent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appsettings",
            name="minimum_withdrawal",
        ),
    ]
