# Generated by Django 5.2.6 on 2025-12-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_review_order"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userbalance",
            name="api_userbal_user_id_4b87c4_idx",
        ),
        migrations.RemoveIndex(
            model_name="userbalance",
            name="api_userbal_user_id_d918c2_idx",
        ),
        migrations.AlterUniqueTogether(
            name="userbalance",
            unique_together={("user", "currency")},
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="account_name",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="account_number",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="bank_name",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="userbalance",
            index=models.Index(fields=["user"], name="api_userbal_user_id_24ea92_idx"),
        ),
        migrations.AddIndex(
            model_name="userbalance",
            index=models.Index(
                fields=["user", "currency"], name="api_userbal_user_id_381653_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="userbalance",
            name="balance_type",
        ),
    ]
