# Generated by Django 5.2.6 on 2026-01-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_appsettings_minimum_withdrawal"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddIndex(
            model_name="deliveryaddress",
            index=models.Index(
                fields=["user", "-created_at"], name="addr_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryaddress",
            index=models.Index(
                fields=["user", "is_default"], name="addr_user_default_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["city", "available"], name="meal_city_available_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["restaurant", "available"], name="meal_restaurant_avail_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(fields=["code"], name="meal_code_idx"),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["available", "-created_at"], name="meal_available_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["city", "available", "price"], name="meal_city_avail_price_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealpreference",
            index=models.Index(
                fields=["user", "preference"], name="pref_user_pref_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealpreference",
            index=models.Index(
                fields=["meal", "preference"], name="pref_meal_pref_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealpreference",
            index=models.Index(
                fields=["user", "-created_at"], name="pref_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["user", "-created_at"], name="msg_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["user", "role"], name="msg_user_role_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["user", "role", "-created_at"], name="msg_user_role_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["message_id"], name="msg_message_id_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["user", "current_intent"], name="msg_user_intent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="order_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "paid"], name="order_user_paid_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "paid", "-created_at"],
                name="order_user_paid_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["code"], name="order_code_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created_at"], name="order_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "day", "time_of_day"], name="rec_user_day_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "sent_to_user"], name="rec_user_sent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "-created_at"], name="rec_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "day", "sent_to_user"], name="rec_user_day_sent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["meal", "day"], name="rec_meal_day_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "time_of_day", "-created_at"],
                name="rec_user_time_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "-created_at"], name="review_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["order"], name="review_order_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["sentiment", "-created_at"], name="review_sentiment_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "sentiment"], name="review_user_sentiment_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="user_phone_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["code"], name="user_code_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["city", "is_active"], name="user_city_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_blocked"], name="user_blocked_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["referred_by"], name="user_referred_by_idx"),
        ),
    ]
