# Generated by Django 5.2.6 on 2025-12-01 15:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.gis.geos import Point


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_userbalance_api_userbal_user_id_4b87c4_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="address",
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0, 0, srid=4326), srid=4326),
            preserve_default=False,
        ),
    ]
