# Generated by Django 5.2.6 on 2025-12-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_userbalance_api_userbal_user_id_4b87c4_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="address",
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="point",
            field=models.JSONField(blank=True, null=True, help_text="GeoJSON Point"),
        ),
    ]
