# Generated by Django 5.2.6 on 2025-12-01 19:29

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_restaurant_address_alter_restaurant_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="available_from_time",
            field=models.TimeField(
                blank=True,
                help_text="Time when this meal becomes available (e.g., 06:00 for breakfast). Leave empty for no time restriction.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="available_to_time",
            field=models.TimeField(
                blank=True,
                help_text="Time when this meal stops being available (e.g., 11:00 for breakfast). Leave empty for no time restriction.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="daily_stock_limit",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of this meal that can be ordered per day. Leave empty for unlimited stock.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="remaining_stock",
            field=models.IntegerField(
                blank=True,
                help_text="Current remaining stock for today. Auto-resets daily via cron job.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="available_days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("monday", "Monday"),
                        ("tuesday", "Tuesday"),
                        ("wednesday", "Wednesday"),
                        ("thursday", "Thursday"),
                        ("friday", "Friday"),
                        ("saturday", "Saturday"),
                        ("sunday", "Sunday"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                help_text="Days when restaurant is open (empty = open all days)",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="close_time",
            field=models.TimeField(
                default=datetime.time(22, 0),
                help_text="Restaurant closing time (default: 22:00)",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="inactive",
            field=models.BooleanField(
                default=False,
                help_text="Set to True to disable this restaurant and all its meals",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="open_time",
            field=models.TimeField(
                default=datetime.time(6, 0),
                help_text="Restaurant opening time (default: 06:00)",
            ),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
