# Generated by Django 5.2.6 on 2026-01-04 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_order_confirmation_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("password_reset", "Password Reset")],
                        default="password_reset",
                        max_length=40,
                    ),
                ),
                ("code", models.CharField(max_length=8)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PasswordReset",
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(fields=["user", "code"], name="pwd_reset_user_code_idx"),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(fields=["expires_at"], name="pwd_reset_expires_idx"),
        ),
    ]
