# Generated by Django 5.2.6 on 2026-01-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_otpcode_delete_passwordreset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="active_riders",
        ),
        migrations.RemoveField(
            model_name="company",
            name="completed_today",
        ),
        migrations.RemoveField(
            model_name="company",
            name="total_orders",
        ),
        migrations.RemoveField(
            model_name="company",
            name="total_revenue",
        ),
        migrations.RemoveField(
            model_name="rider",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="rider",
            name="completed_today",
        ),
        migrations.RemoveField(
            model_name="rider",
            name="total_deliveries",
        ),
        migrations.RemoveField(
            model_name="rider",
            name="total_earnings",
        ),
        migrations.AlterField(
            model_name="order",
            name="confirmation_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
