# Generated by Django 5.2.6 on 2025-12-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_meal_available_from_time_meal_available_to_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="delivery_fee_per_km",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
