# Generated by Django 5.2.6 on 2026-01-05 10:37

import api.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_remove_company_active_riders_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="rider",
            name="rider_online_idx",
        ),
        migrations.RemoveIndex(
            model_name="rider",
            name="rider_online_company_idx",
        ),
        migrations.RemoveField(
            model_name="rider",
            name="is_online",
        ),
        migrations.RemoveField(
            model_name="rider",
            name="is_verified",
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.JSONField(
                default=list,  # Default to empty list
                help_text="List of user roles: ['customer'], ['rider'], ['company'], or combinations",
            ),
        ),
    ]
