# Generated by Django 5.2.6 on 2025-12-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_city_delivery_fee_per_km"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="min_delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
