# Generated by Django 5.2.6 on 2025-12-02 14:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_city_min_delivery_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="image_url",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="current_intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_intent", "No intent"),
                    ("needs_reply", "Needs reply"),
                    ("reminder_message", "Reminder message"),
                    ("flow_message", "Flow message"),
                    ("completed_reply", "Completed reply"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
