# Generated by Django 5.2.6 on 2025-12-02 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_meal_image_url_alter_message_current_intent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialOccasion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the occasion (e.g., 'Christmas Day', 'New Year's Eve')",
                        max_length=255,
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        help_text="Month (1-12) for recurring annual occasions"
                    ),
                ),
                ("day", models.IntegerField(help_text="Day of month (1-31)")),
                (
                    "year",
                    models.IntegerField(
                        blank=True,
                        help_text="Specific year (leave blank for recurring annual occasion)",
                        null=True,
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=True,
                        help_text="If True, this occasion repeats every year",
                    ),
                ),
                (
                    "boost_weight",
                    models.FloatField(
                        default=50.0,
                        help_text="Score boost to apply (e.g., 50.0 for strong boost, 20.0 for moderate)",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable this occasion without deleting",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or notes about this occasion",
                    ),
                ),
                (
                    "cities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Cities where this occasion applies (leave empty for all cities)",
                        related_name="special_occasions",
                        to="api.city",
                    ),
                ),
                (
                    "meals",
                    models.ManyToManyField(
                        help_text="Meals to boost for this occasion",
                        related_name="special_occasions",
                        to="api.meal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Occasion",
                "verbose_name_plural": "Special Occasions",
                "ordering": ["month", "day"],
                "indexes": [
                    models.Index(
                        fields=["month", "day", "active"],
                        name="api_special_month_0b2423_idx",
                    ),
                    models.Index(
                        fields=["year", "active"], name="api_special_year_e949a1_idx"
                    ),
                ],
            },
        ),
    ]
