# Generated by Django 5.2.6 on 2026-01-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_user_is_online_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="rider_assigned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when rider was assigned to this order",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["rider", "status", "rider_assigned_at"],
                name="order_rider_timeout_idx",
            ),
        ),
    ]
