# Generated by Django 5.2.6 on 2025-12-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_specialoccasion"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="rider_company",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="rider_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="rider_note",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="rider_phone",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="note",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
