# Generated by Django 5.2.6 on 2026-01-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_order_rider_assigned_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this rider belongs to another rider who acts as their company",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_riders",
                to="api.rider",
            ),
        ),
        migrations.AddField(
            model_name="rider",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Company name if this rider manages other riders",
                max_length=255,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
