# Generated by Django 5.2.6 on 2026-01-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_rider_company_rider_company_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="roles",
        ),
    ]
