# Generated by Django 5.2.6 on 2025-12-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_order_rider_company_order_rider_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="embedding",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="embedding_generated_at",
        ),
    ]
