# Generated by Django 5.2.6 on 2025-12-13 16:55

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_remove_meal_embedding_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealEmbedding",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="embedding_cache",
                        serialize=False,
                        to="api.meal",
                    ),
                ),
                (
                    "embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        help_text="OpenAI embedding vector for semantic similarity",
                        size=1536,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="MD5 hash of meal attributes used for embedding",
                        max_length=32,
                    ),
                ),
                (
                    "embedding_text",
                    models.TextField(
                        blank=True,
                        help_text="The text that was sent to OpenAI for embedding (truncated)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal Embedding",
                "verbose_name_plural": "Meal Embeddings",
            },
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="minimum_withdrawal",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="city",
            name="average_meal_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="delivery_fee_per_km",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="city",
            name="min_delivery_fee",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="city",
            name="referral_bonus",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="meal",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="meal_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="referralearning",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="user",
            name="average_meal_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userbalance",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Balance amount in the specified currency",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
