# Generated by Django 5.2.6 on 2026-01-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_remove_user_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="mealembedding",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Meal Embedding",
                "verbose_name_plural": "Meal Embeddings",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="otpcode",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="refreshtoken",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="rider",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
    ]
