# Generated by Django 5.2.6 on 2026-01-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_message_current_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="current_intent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_intent", "No intent"),
                    ("needs_reply", "Needs reply"),
                    ("reminder_message", "Reminder message"),
                    ("flow_message", "Flow message"),
                    ("completed_reply", "Completed reply"),
                    ("progress_stats_reminder", "Progress stats reminder"),
                    ("welcome_bonus_message", "Welcome bonus message"),
                    ("no_meal_to_recommend_message", "No meal to recommend Message"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
