"""
Django settings for foodie_robot project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import cloudinary

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
TRY_LOCAL_DB = config('TRY_LOCAL_DB', default=False, cast=bool)
TRY_LOCAL_SETTING = config('TRY_LOCAL_SETTING', default=False, cast=bool)

MAPBOX_TOKEN = config('MAPBOX_TOKEN')

ZOHO_ZEPTOMAIL_KEY = config('ZOHO_ZEPTOMAIL_KEY')
ALLOWED_HOSTS = []

if DEBUG:
    ALLOWED_HOSTS = ['127.0.0.1', '10.71.154.9', 'localhost', '.ngrok-free.app']

_ALLOWED_HOST = config('ALLOWED_HOST', '')
ALLOWED_HOSTS.extend(_ALLOWED_HOST.split())

TRY_LOCAL_DEV_PAYMENT = config('TRY_LOCAL_DEV_PAYMENT', default=False, cast=bool)

WHATSAPP_MESSAGE_BASE_URL = config('WHATSAPP_MESSAGE_BASE_URL')
WHATSAPP_API_KEY = config('WHATSAPP_API_KEY')
WHATSAPP_API_VERIFY_TOKEN = config('WHATSAPP_API_VERIFY_TOKEN')
WHATSAPP_PHONE_NUMBER_ID = config('WHATSAPP_PHONE_NUMBER_ID')
WHATSAPP_APP_SECRET = config('WHATSAPP_APP_SECRET')

WHATSAPP_FLOW_PRIVATE_KEY_PATH = config('WHATSAPP_FLOW_PRIVATE_KEY_PATH', default=str(BASE_DIR / 'private_key.pem'))
WHATSAPP_FLOW_PUBLIC_KEY_PATH = config('WHATSAPP_FLOW_PUBLIC_KEY_PATH', default=str(BASE_DIR / 'public_key.pem'))

# WhatsApp Flow IDs
WHATSAPP_FLOW_USER_PROFILE = config('WHATSAPP_FLOW_USER_PROFILE')
WHATSAPP_FLOW_ORDER_REVIEW = config('WHATSAPP_FLOW_ORDER_REVIEW')
WHATSAPP_FLOW_WITHDRAWAL = config('WHATSAPP_FLOW_WITHDRAWAL')
WHATSAPP_FLOW_ORDER = config('WHATSAPP_FLOW_ORDER')

VENDY_PUBLIC_KEY = config('VENDY_PUBLIC_KEY')
VENDY_SECRET_HASH = config('VENDY_SECRET_HASH')

OPENAI_API_KEY = config('OPENAI_API_KEY')

DASHSCOPE_API_KEY = config('DASHSCOPE_API_KEY')

# ---------------------------------------------------------------------------
# Alibaba Cloud Model Studio (DashScope) configuration
# ---------------------------------------------------------------------------
# AI calls (chat/tool-calling, vision, embeddings) are served by Alibaba Cloud
# Qwen models via the DashScope API.
AI_API_KEY = config('AI_API_KEY', default=DASHSCOPE_API_KEY)
# DashScope API host. For the China (mainland) region drop the "-intl".
AI_BASE_URL = config(
    'AI_BASE_URL',
    default='https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
)
AI_CHAT_MODEL = config('AI_CHAT_MODEL', default='qwen-max')          # orchestrator / tool calling
AI_VISION_MODEL = config('AI_VISION_MODEL', default='qwen-vl-max')   # meal image analysis
AI_EMBEDDING_MODEL = config('AI_EMBEDDING_MODEL', default='text-embedding-v4')
AI_EMBEDDING_DIMENSIONS = config('AI_EMBEDDING_DIMENSIONS', default=1536, cast=int)
# Max inputs per DashScope embeddings request.
AI_EMBEDDING_BATCH_SIZE = config('AI_EMBEDDING_BATCH_SIZE', default=10, cast=int)
AI_REASONING_EFFORT = config('AI_REASONING_EFFORT', default='')

# Cloudinary Configuration
CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME')
CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET')

cloudinary.config(
    cloud_name=CLOUDINARY_CLOUD_NAME,
    api_key=CLOUDINARY_API_KEY,
    api_secret=CLOUDINARY_API_SECRET,
    secure=True
)

# django-cloudinary-storage configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
    'API_KEY': CLOUDINARY_API_KEY,
    'API_SECRET': CLOUDINARY_API_SECRET,
}

# Application definition

INSTALLED_APPS = [
    "daphne",
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "corsheaders",
    "cloudinary_storage",
    "cloudinary",
    "huey.contrib.djhuey",
    "api"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "foodie_robot.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "foodie_robot.wsgi.application"
ASGI_APPLICATION = "foodie_robot.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if TRY_LOCAL_DB:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': config('DATABASES_DEFAULT_ENGINE'),
            'NAME': config('DATABASES_DEFAULT_NAME'),
            'HOST': config('DATABASES_DEFAULT_HOST'),
            'PORT': config('DATABASES_DEFAULT_PORT', cast=int),
            'USER': config('DATABASES_DEFAULT_USER'),
            'PASSWORD': config('DATABASES_DEFAULT_PASSWORD'),
        }
    }

# Cache Configuration
# https://docs.djangoproject.com/en/5.2/topics/cache/
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'api_cache_table',
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
            'CULL_FREQUENCY': 4,  # Remove 1/4 of entries when MAX_ENTRIES is reached
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Media files configuration
MEDIA_URL = '/media/'

# Storage configuration (Django 5.x)
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# USER MODEL
AUTH_USER_MODEL = 'api.User'

# CORS
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

# Flutter Web CORS Origins
# Production
FLUTTER_PRODUCTION_DOMAINS = [
    'rider.foodierobot.com',
]

# Local development (Flutter web typically runs on these ports)
FLUTTER_LOCAL_ORIGINS = [
    'http://127.0.0.1:52240',
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^https://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
    r"^https://127\.0\.0\.1:\d+$",
] if DEBUG else []
CORS_ALLOWED_ORIGINS = []
CSRF_TRUSTED_ORIGINS = []

# Add Flutter production domains
for domain in FLUTTER_PRODUCTION_DOMAINS:
    CSRF_TRUSTED_ORIGINS.append(f'https://{domain}')
    CORS_ALLOWED_ORIGINS.append(f'https://{domain}')

# Add Flutter local development origins
if DEBUG:
    CORS_ALLOWED_ORIGINS.extend(FLUTTER_LOCAL_ORIGINS)
    CSRF_TRUSTED_ORIGINS.extend(FLUTTER_LOCAL_ORIGINS)

# Add backend allowed hosts
for host in _ALLOWED_HOST.split():
    CSRF_TRUSTED_ORIGINS.append(f'http://{host}')
    CSRF_TRUSTED_ORIGINS.append(f'https://{host}')
    CORS_ALLOWED_ORIGINS.append(f'http://{host}')
    CORS_ALLOWED_ORIGINS.append(f'https://{host}')

# Additional CORS headers for Flutter web
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrf-token',
]


# Huey Configuration
# For Koyeb workers, use Redis as the backend
REDIS_URL = config('REDIS_URL', default='')

# HUEY_IMMEDIATE: Set to False in production, True only for local testing without Redis
# When True, tasks run synchronously (no Redis needed)
# When False, tasks are queued to Redis (required for run_huey consumer)
# Auto-enable immediate mode if no REDIS_URL is provided (for local dev)
HUEY_IMMEDIATE = config('HUEY_IMMEDIATE', default=not bool(REDIS_URL), cast=bool)

from huey import RedisHuey

HUEY = RedisHuey(
    'foodie_robot',
    url=REDIS_URL or 'redis://localhost:6379/0',
    immediate=HUEY_IMMEDIATE,
    # read_timeout sets BRPOP timeout in seconds (default is 1)
    # Higher value = fewer Redis commands, but slower task pickup
    # 60 seconds reduces BRPOP calls from 60/min to 1/min
    read_timeout=60,
)

# Huey consumer settings documentation
# To reduce Redis commands, use these flags when running Huey:
#   python manage.py run_huey --health-check-interval 60 --scheduler-interval 60
#
# --scheduler-interval: How often to check for scheduled/periodic tasks (default: 1)
# read_timeout=60 in RedisHuey: BRPOP timeout in seconds (default: 1)
#
# Combined effect:
# - BRPOP: 1 command per 60 seconds (instead of 60/min)
# - Scheduler check: 1 per 60 seconds (instead of 60/min)
# - Total: ~2-3 commands/minute instead of ~260/minute

# Channels Configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL or "redis://localhost:6379/0"],
        },
    },
}

# JWT Configuration for Rider/Company API
JWT_SECRET_KEY = config('JWT_SECRET_KEY', default=SECRET_KEY)
JWT_ACCESS_TOKEN_EXPIRY_HOURS = 24  # Access token expires after 24 hours

# Jazzmin Admin Configuration
JAZZMIN_SETTINGS = {
    "site_title": "FoodieRobot Admin",
    "site_header": "FoodieRobot",
    "site_brand": "FoodieRobot",
    "welcome_sign": "Welcome to FoodieRobot Admin",
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "api.user": "fas fa-users",
        "api.order": "fas fa-shopping-cart",
        "api.meal": "fas fa-utensils",
        "api.message": "fas fa-comments",
        "api.restaurant": "fas fa-store",
        "api.recommendation": "fas fa-thumbs-up",
        "api.review": "fas fa-star",
    },
    "custom_links": {
        "api": [{
            "name": "Send Template Messages",
            "url": "admin:send_template",
            "icon": "fas fa-paper-plane",
            "permissions": ["api.view_user"]
        }]
    },
}
