from api.models.user import *
from api.models.meal import *
from api.models.order import *
from api.models.recommendation import *
from api.models.location import *
from api.models.address import *
from api.models.review import *
from api.models.currency import *
from api.models.message import *
from api.models.meal_preference import *
from api.models.restaurant import *
